/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing AnonymousAccessSettingsXO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnonymousAccessSettingsXOTests
    {
        // TODO uncomment below to declare an instance variable for AnonymousAccessSettingsXO
        //private AnonymousAccessSettingsXO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnonymousAccessSettingsXO
            //instance = new AnonymousAccessSettingsXO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnonymousAccessSettingsXO
        /// </summary>
        [Test]
        public void AnonymousAccessSettingsXOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnonymousAccessSettingsXO
            //Assert.IsInstanceOfType<AnonymousAccessSettingsXO> (instance, "variable 'instance' is a AnonymousAccessSettingsXO");
        }


        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'RealmName'
        /// </summary>
        [Test]
        public void RealmNameTest()
        {
            // TODO unit test for the property 'RealmName'
        }

    }

}
