/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ApiCertificate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiCertificateTests
    {
        // TODO uncomment below to declare an instance variable for ApiCertificate
        //private ApiCertificate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiCertificate
            //instance = new ApiCertificate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiCertificate
        /// </summary>
        [Test]
        public void ApiCertificateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiCertificate
            //Assert.IsInstanceOfType<ApiCertificate> (instance, "variable 'instance' is a ApiCertificate");
        }


        /// <summary>
        /// Test the property 'ExpiresOn'
        /// </summary>
        [Test]
        public void ExpiresOnTest()
        {
            // TODO unit test for the property 'ExpiresOn'
        }
        /// <summary>
        /// Test the property 'Fingerprint'
        /// </summary>
        [Test]
        public void FingerprintTest()
        {
            // TODO unit test for the property 'Fingerprint'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IssuedOn'
        /// </summary>
        [Test]
        public void IssuedOnTest()
        {
            // TODO unit test for the property 'IssuedOn'
        }
        /// <summary>
        /// Test the property 'IssuerCommonName'
        /// </summary>
        [Test]
        public void IssuerCommonNameTest()
        {
            // TODO unit test for the property 'IssuerCommonName'
        }
        /// <summary>
        /// Test the property 'IssuerOrganization'
        /// </summary>
        [Test]
        public void IssuerOrganizationTest()
        {
            // TODO unit test for the property 'IssuerOrganization'
        }
        /// <summary>
        /// Test the property 'IssuerOrganizationalUnit'
        /// </summary>
        [Test]
        public void IssuerOrganizationalUnitTest()
        {
            // TODO unit test for the property 'IssuerOrganizationalUnit'
        }
        /// <summary>
        /// Test the property 'Pem'
        /// </summary>
        [Test]
        public void PemTest()
        {
            // TODO unit test for the property 'Pem'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'SubjectCommonName'
        /// </summary>
        [Test]
        public void SubjectCommonNameTest()
        {
            // TODO unit test for the property 'SubjectCommonName'
        }
        /// <summary>
        /// Test the property 'SubjectOrganization'
        /// </summary>
        [Test]
        public void SubjectOrganizationTest()
        {
            // TODO unit test for the property 'SubjectOrganization'
        }
        /// <summary>
        /// Test the property 'SubjectOrganizationalUnit'
        /// </summary>
        [Test]
        public void SubjectOrganizationalUnitTest()
        {
            // TODO unit test for the property 'SubjectOrganizationalUnit'
        }

    }

}
