/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ApiEmailConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiEmailConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for ApiEmailConfiguration
        //private ApiEmailConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiEmailConfiguration
            //instance = new ApiEmailConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiEmailConfiguration
        /// </summary>
        [Test]
        public void ApiEmailConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiEmailConfiguration
            //Assert.IsInstanceOfType<ApiEmailConfiguration> (instance, "variable 'instance' is a ApiEmailConfiguration");
        }


        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'FromAddress'
        /// </summary>
        [Test]
        public void FromAddressTest()
        {
            // TODO unit test for the property 'FromAddress'
        }
        /// <summary>
        /// Test the property 'SubjectPrefix'
        /// </summary>
        [Test]
        public void SubjectPrefixTest()
        {
            // TODO unit test for the property 'SubjectPrefix'
        }
        /// <summary>
        /// Test the property 'StartTlsEnabled'
        /// </summary>
        [Test]
        public void StartTlsEnabledTest()
        {
            // TODO unit test for the property 'StartTlsEnabled'
        }
        /// <summary>
        /// Test the property 'StartTlsRequired'
        /// </summary>
        [Test]
        public void StartTlsRequiredTest()
        {
            // TODO unit test for the property 'StartTlsRequired'
        }
        /// <summary>
        /// Test the property 'SslOnConnectEnabled'
        /// </summary>
        [Test]
        public void SslOnConnectEnabledTest()
        {
            // TODO unit test for the property 'SslOnConnectEnabled'
        }
        /// <summary>
        /// Test the property 'SslServerIdentityCheckEnabled'
        /// </summary>
        [Test]
        public void SslServerIdentityCheckEnabledTest()
        {
            // TODO unit test for the property 'SslServerIdentityCheckEnabled'
        }
        /// <summary>
        /// Test the property 'NexusTrustStoreEnabled'
        /// </summary>
        [Test]
        public void NexusTrustStoreEnabledTest()
        {
            // TODO unit test for the property 'NexusTrustStoreEnabled'
        }

    }

}
