/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ApiLicenseDetailsXO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiLicenseDetailsXOTests
    {
        // TODO uncomment below to declare an instance variable for ApiLicenseDetailsXO
        //private ApiLicenseDetailsXO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiLicenseDetailsXO
            //instance = new ApiLicenseDetailsXO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiLicenseDetailsXO
        /// </summary>
        [Test]
        public void ApiLicenseDetailsXOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiLicenseDetailsXO
            //Assert.IsInstanceOfType<ApiLicenseDetailsXO> (instance, "variable 'instance' is a ApiLicenseDetailsXO");
        }


        /// <summary>
        /// Test the property 'ContactEmail'
        /// </summary>
        [Test]
        public void ContactEmailTest()
        {
            // TODO unit test for the property 'ContactEmail'
        }
        /// <summary>
        /// Test the property 'ContactCompany'
        /// </summary>
        [Test]
        public void ContactCompanyTest()
        {
            // TODO unit test for the property 'ContactCompany'
        }
        /// <summary>
        /// Test the property 'ContactName'
        /// </summary>
        [Test]
        public void ContactNameTest()
        {
            // TODO unit test for the property 'ContactName'
        }
        /// <summary>
        /// Test the property 'EffectiveDate'
        /// </summary>
        [Test]
        public void EffectiveDateTest()
        {
            // TODO unit test for the property 'EffectiveDate'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Test]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'LicenseType'
        /// </summary>
        [Test]
        public void LicenseTypeTest()
        {
            // TODO unit test for the property 'LicenseType'
        }
        /// <summary>
        /// Test the property 'LicensedUsers'
        /// </summary>
        [Test]
        public void LicensedUsersTest()
        {
            // TODO unit test for the property 'LicensedUsers'
        }
        /// <summary>
        /// Test the property 'Fingerprint'
        /// </summary>
        [Test]
        public void FingerprintTest()
        {
            // TODO unit test for the property 'Fingerprint'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Test]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

    }

}
