/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ApiPrivilegeWildcardRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiPrivilegeWildcardRequestTests
    {
        // TODO uncomment below to declare an instance variable for ApiPrivilegeWildcardRequest
        //private ApiPrivilegeWildcardRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiPrivilegeWildcardRequest
            //instance = new ApiPrivilegeWildcardRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiPrivilegeWildcardRequest
        /// </summary>
        [Test]
        public void ApiPrivilegeWildcardRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiPrivilegeWildcardRequest
            //Assert.IsInstanceOfType<ApiPrivilegeWildcardRequest> (instance, "variable 'instance' is a ApiPrivilegeWildcardRequest");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Pattern'
        /// </summary>
        [Test]
        public void PatternTest()
        {
            // TODO unit test for the property 'Pattern'
        }

    }

}
