/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing AptHostedRepositoryApiRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AptHostedRepositoryApiRequestTests
    {
        // TODO uncomment below to declare an instance variable for AptHostedRepositoryApiRequest
        //private AptHostedRepositoryApiRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AptHostedRepositoryApiRequest
            //instance = new AptHostedRepositoryApiRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AptHostedRepositoryApiRequest
        /// </summary>
        [Test]
        public void AptHostedRepositoryApiRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AptHostedRepositoryApiRequest
            //Assert.IsInstanceOfType<AptHostedRepositoryApiRequest> (instance, "variable 'instance' is a AptHostedRepositoryApiRequest");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Online'
        /// </summary>
        [Test]
        public void OnlineTest()
        {
            // TODO unit test for the property 'Online'
        }
        /// <summary>
        /// Test the property 'Storage'
        /// </summary>
        [Test]
        public void StorageTest()
        {
            // TODO unit test for the property 'Storage'
        }
        /// <summary>
        /// Test the property 'Cleanup'
        /// </summary>
        [Test]
        public void CleanupTest()
        {
            // TODO unit test for the property 'Cleanup'
        }
        /// <summary>
        /// Test the property 'Apt'
        /// </summary>
        [Test]
        public void AptTest()
        {
            // TODO unit test for the property 'Apt'
        }
        /// <summary>
        /// Test the property 'AptSigning'
        /// </summary>
        [Test]
        public void AptSigningTest()
        {
            // TODO unit test for the property 'AptSigning'
        }

    }

}
