/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing AptProxyRepositoriesAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AptProxyRepositoriesAttributesTests
    {
        // TODO uncomment below to declare an instance variable for AptProxyRepositoriesAttributes
        //private AptProxyRepositoriesAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AptProxyRepositoriesAttributes
            //instance = new AptProxyRepositoriesAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AptProxyRepositoriesAttributes
        /// </summary>
        [Test]
        public void AptProxyRepositoriesAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AptProxyRepositoriesAttributes
            //Assert.IsInstanceOfType<AptProxyRepositoriesAttributes> (instance, "variable 'instance' is a AptProxyRepositoriesAttributes");
        }


        /// <summary>
        /// Test the property 'Distribution'
        /// </summary>
        [Test]
        public void DistributionTest()
        {
            // TODO unit test for the property 'Distribution'
        }
        /// <summary>
        /// Test the property 'Flat'
        /// </summary>
        [Test]
        public void FlatTest()
        {
            // TODO unit test for the property 'Flat'
        }

    }

}
