/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing AptSigningRepositoriesAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AptSigningRepositoriesAttributesTests
    {
        // TODO uncomment below to declare an instance variable for AptSigningRepositoriesAttributes
        //private AptSigningRepositoriesAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AptSigningRepositoriesAttributes
            //instance = new AptSigningRepositoriesAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AptSigningRepositoriesAttributes
        /// </summary>
        [Test]
        public void AptSigningRepositoriesAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AptSigningRepositoriesAttributes
            //Assert.IsInstanceOfType<AptSigningRepositoriesAttributes> (instance, "variable 'instance' is a AptSigningRepositoriesAttributes");
        }


        /// <summary>
        /// Test the property 'Keypair'
        /// </summary>
        [Test]
        public void KeypairTest()
        {
            // TODO unit test for the property 'Keypair'
        }
        /// <summary>
        /// Test the property 'Passphrase'
        /// </summary>
        [Test]
        public void PassphraseTest()
        {
            // TODO unit test for the property 'Passphrase'
        }

    }

}
