/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing BlobStoreQuotaResultXO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BlobStoreQuotaResultXOTests
    {
        // TODO uncomment below to declare an instance variable for BlobStoreQuotaResultXO
        //private BlobStoreQuotaResultXO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BlobStoreQuotaResultXO
            //instance = new BlobStoreQuotaResultXO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlobStoreQuotaResultXO
        /// </summary>
        [Test]
        public void BlobStoreQuotaResultXOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BlobStoreQuotaResultXO
            //Assert.IsInstanceOfType<BlobStoreQuotaResultXO> (instance, "variable 'instance' is a BlobStoreQuotaResultXO");
        }


        /// <summary>
        /// Test the property 'IsViolation'
        /// </summary>
        [Test]
        public void IsViolationTest()
        {
            // TODO unit test for the property 'IsViolation'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'BlobStoreName'
        /// </summary>
        [Test]
        public void BlobStoreNameTest()
        {
            // TODO unit test for the property 'BlobStoreName'
        }

    }

}
