/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing BlobStoreApiSoftQuota
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BlobStoreApiSoftQuotaTests
    {
        // TODO uncomment below to declare an instance variable for BlobStoreApiSoftQuota
        //private BlobStoreApiSoftQuota instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BlobStoreApiSoftQuota
            //instance = new BlobStoreApiSoftQuota();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlobStoreApiSoftQuota
        /// </summary>
        [Test]
        public void BlobStoreApiSoftQuotaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BlobStoreApiSoftQuota
            //Assert.IsInstanceOfType<BlobStoreApiSoftQuota> (instance, "variable 'instance' is a BlobStoreApiSoftQuota");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

    }

}
