/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing BowerAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BowerAttributesTests
    {
        // TODO uncomment below to declare an instance variable for BowerAttributes
        //private BowerAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BowerAttributes
            //instance = new BowerAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BowerAttributes
        /// </summary>
        [Test]
        public void BowerAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BowerAttributes
            //Assert.IsInstanceOfType<BowerAttributes> (instance, "variable 'instance' is a BowerAttributes");
        }


        /// <summary>
        /// Test the property 'RewritePackageUrls'
        /// </summary>
        [Test]
        public void RewritePackageUrlsTest()
        {
            // TODO unit test for the property 'RewritePackageUrls'
        }

    }

}
