/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing CleanupPolicyAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CleanupPolicyAttributesTests
    {
        // TODO uncomment below to declare an instance variable for CleanupPolicyAttributes
        //private CleanupPolicyAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CleanupPolicyAttributes
            //instance = new CleanupPolicyAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CleanupPolicyAttributes
        /// </summary>
        [Test]
        public void CleanupPolicyAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CleanupPolicyAttributes
            //Assert.IsInstanceOfType<CleanupPolicyAttributes> (instance, "variable 'instance' is a CleanupPolicyAttributes");
        }


        /// <summary>
        /// Test the property 'PolicyNames'
        /// </summary>
        [Test]
        public void PolicyNamesTest()
        {
            // TODO unit test for the property 'PolicyNames'
        }

    }

}
