/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing DockerAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DockerAttributesTests
    {
        // TODO uncomment below to declare an instance variable for DockerAttributes
        //private DockerAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DockerAttributes
            //instance = new DockerAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DockerAttributes
        /// </summary>
        [Test]
        public void DockerAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DockerAttributes
            //Assert.IsInstanceOfType<DockerAttributes> (instance, "variable 'instance' is a DockerAttributes");
        }


        /// <summary>
        /// Test the property 'V1Enabled'
        /// </summary>
        [Test]
        public void V1EnabledTest()
        {
            // TODO unit test for the property 'V1Enabled'
        }
        /// <summary>
        /// Test the property 'ForceBasicAuth'
        /// </summary>
        [Test]
        public void ForceBasicAuthTest()
        {
            // TODO unit test for the property 'ForceBasicAuth'
        }
        /// <summary>
        /// Test the property 'HttpPort'
        /// </summary>
        [Test]
        public void HttpPortTest()
        {
            // TODO unit test for the property 'HttpPort'
        }
        /// <summary>
        /// Test the property 'HttpsPort'
        /// </summary>
        [Test]
        public void HttpsPortTest()
        {
            // TODO unit test for the property 'HttpsPort'
        }

    }

}
