/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing DockerProxyAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DockerProxyAttributesTests
    {
        // TODO uncomment below to declare an instance variable for DockerProxyAttributes
        //private DockerProxyAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DockerProxyAttributes
            //instance = new DockerProxyAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DockerProxyAttributes
        /// </summary>
        [Test]
        public void DockerProxyAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DockerProxyAttributes
            //Assert.IsInstanceOfType<DockerProxyAttributes> (instance, "variable 'instance' is a DockerProxyAttributes");
        }


        /// <summary>
        /// Test the property 'IndexType'
        /// </summary>
        [Test]
        public void IndexTypeTest()
        {
            // TODO unit test for the property 'IndexType'
        }
        /// <summary>
        /// Test the property 'IndexUrl'
        /// </summary>
        [Test]
        public void IndexUrlTest()
        {
            // TODO unit test for the property 'IndexUrl'
        }

    }

}
