/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing FileBlobStoreApiModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileBlobStoreApiModelTests
    {
        // TODO uncomment below to declare an instance variable for FileBlobStoreApiModel
        //private FileBlobStoreApiModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileBlobStoreApiModel
            //instance = new FileBlobStoreApiModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileBlobStoreApiModel
        /// </summary>
        [Test]
        public void FileBlobStoreApiModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileBlobStoreApiModel
            //Assert.IsInstanceOfType<FileBlobStoreApiModel> (instance, "variable 'instance' is a FileBlobStoreApiModel");
        }


        /// <summary>
        /// Test the property 'SoftQuota'
        /// </summary>
        [Test]
        public void SoftQuotaTest()
        {
            // TODO unit test for the property 'SoftQuota'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
