/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing GenericBlobStoreApiResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GenericBlobStoreApiResponseTests
    {
        // TODO uncomment below to declare an instance variable for GenericBlobStoreApiResponse
        //private GenericBlobStoreApiResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenericBlobStoreApiResponse
            //instance = new GenericBlobStoreApiResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenericBlobStoreApiResponse
        /// </summary>
        [Test]
        public void GenericBlobStoreApiResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GenericBlobStoreApiResponse
            //Assert.IsInstanceOfType<GenericBlobStoreApiResponse> (instance, "variable 'instance' is a GenericBlobStoreApiResponse");
        }


        /// <summary>
        /// Test the property 'SoftQuota'
        /// </summary>
        [Test]
        public void SoftQuotaTest()
        {
            // TODO unit test for the property 'SoftQuota'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'BlobCount'
        /// </summary>
        [Test]
        public void BlobCountTest()
        {
            // TODO unit test for the property 'BlobCount'
        }
        /// <summary>
        /// Test the property 'TotalSizeInBytes'
        /// </summary>
        [Test]
        public void TotalSizeInBytesTest()
        {
            // TODO unit test for the property 'TotalSizeInBytes'
        }
        /// <summary>
        /// Test the property 'AvailableSpaceInBytes'
        /// </summary>
        [Test]
        public void AvailableSpaceInBytesTest()
        {
            // TODO unit test for the property 'AvailableSpaceInBytes'
        }

    }

}
