/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing GroupAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupAttributesTests
    {
        // TODO uncomment below to declare an instance variable for GroupAttributes
        //private GroupAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupAttributes
            //instance = new GroupAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupAttributes
        /// </summary>
        [Test]
        public void GroupAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupAttributes
            //Assert.IsInstanceOfType<GroupAttributes> (instance, "variable 'instance' is a GroupAttributes");
        }


        /// <summary>
        /// Test the property 'MemberNames'
        /// </summary>
        [Test]
        public void MemberNamesTest()
        {
            // TODO unit test for the property 'MemberNames'
        }

    }

}
