/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing HttpClientAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpClientAttributesTests
    {
        // TODO uncomment below to declare an instance variable for HttpClientAttributes
        //private HttpClientAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpClientAttributes
            //instance = new HttpClientAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpClientAttributes
        /// </summary>
        [Test]
        public void HttpClientAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpClientAttributes
            //Assert.IsInstanceOfType<HttpClientAttributes> (instance, "variable 'instance' is a HttpClientAttributes");
        }


        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Test]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }
        /// <summary>
        /// Test the property 'AutoBlock'
        /// </summary>
        [Test]
        public void AutoBlockTest()
        {
            // TODO unit test for the property 'AutoBlock'
        }
        /// <summary>
        /// Test the property 'Connection'
        /// </summary>
        [Test]
        public void ConnectionTest()
        {
            // TODO unit test for the property 'Connection'
        }
        /// <summary>
        /// Test the property 'Authentication'
        /// </summary>
        [Test]
        public void AuthenticationTest()
        {
            // TODO unit test for the property 'Authentication'
        }

    }

}
