/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing HttpClientConnectionAuthenticationAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpClientConnectionAuthenticationAttributesTests
    {
        // TODO uncomment below to declare an instance variable for HttpClientConnectionAuthenticationAttributes
        //private HttpClientConnectionAuthenticationAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpClientConnectionAuthenticationAttributes
            //instance = new HttpClientConnectionAuthenticationAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpClientConnectionAuthenticationAttributes
        /// </summary>
        [Test]
        public void HttpClientConnectionAuthenticationAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpClientConnectionAuthenticationAttributes
            //Assert.IsInstanceOfType<HttpClientConnectionAuthenticationAttributes> (instance, "variable 'instance' is a HttpClientConnectionAuthenticationAttributes");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'NtlmHost'
        /// </summary>
        [Test]
        public void NtlmHostTest()
        {
            // TODO unit test for the property 'NtlmHost'
        }
        /// <summary>
        /// Test the property 'NtlmDomain'
        /// </summary>
        [Test]
        public void NtlmDomainTest()
        {
            // TODO unit test for the property 'NtlmDomain'
        }

    }

}
