/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing HttpClientConnectionAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpClientConnectionAttributesTests
    {
        // TODO uncomment below to declare an instance variable for HttpClientConnectionAttributes
        //private HttpClientConnectionAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpClientConnectionAttributes
            //instance = new HttpClientConnectionAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpClientConnectionAttributes
        /// </summary>
        [Test]
        public void HttpClientConnectionAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpClientConnectionAttributes
            //Assert.IsInstanceOfType<HttpClientConnectionAttributes> (instance, "variable 'instance' is a HttpClientConnectionAttributes");
        }


        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Test]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }
        /// <summary>
        /// Test the property 'UserAgentSuffix'
        /// </summary>
        [Test]
        public void UserAgentSuffixTest()
        {
            // TODO unit test for the property 'UserAgentSuffix'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'EnableCircularRedirects'
        /// </summary>
        [Test]
        public void EnableCircularRedirectsTest()
        {
            // TODO unit test for the property 'EnableCircularRedirects'
        }
        /// <summary>
        /// Test the property 'EnableCookies'
        /// </summary>
        [Test]
        public void EnableCookiesTest()
        {
            // TODO unit test for the property 'EnableCookies'
        }

    }

}
