/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing IqConnectionXo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IqConnectionXoTests
    {
        // TODO uncomment below to declare an instance variable for IqConnectionXo
        //private IqConnectionXo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IqConnectionXo
            //instance = new IqConnectionXo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IqConnectionXo
        /// </summary>
        [Test]
        public void IqConnectionXoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IqConnectionXo
            //Assert.IsInstanceOfType<IqConnectionXo> (instance, "variable 'instance' is a IqConnectionXo");
        }


        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'ShowLink'
        /// </summary>
        [Test]
        public void ShowLinkTest()
        {
            // TODO unit test for the property 'ShowLink'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'AuthenticationType'
        /// </summary>
        [Test]
        public void AuthenticationTypeTest()
        {
            // TODO unit test for the property 'AuthenticationType'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'UseTrustStoreForUrl'
        /// </summary>
        [Test]
        public void UseTrustStoreForUrlTest()
        {
            // TODO unit test for the property 'UseTrustStoreForUrl'
        }
        /// <summary>
        /// Test the property 'TimeoutSeconds'
        /// </summary>
        [Test]
        public void TimeoutSecondsTest()
        {
            // TODO unit test for the property 'TimeoutSeconds'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

    }

}
