/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing IqConnectionVerificationXo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IqConnectionVerificationXoTests
    {
        // TODO uncomment below to declare an instance variable for IqConnectionVerificationXo
        //private IqConnectionVerificationXo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IqConnectionVerificationXo
            //instance = new IqConnectionVerificationXo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IqConnectionVerificationXo
        /// </summary>
        [Test]
        public void IqConnectionVerificationXoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IqConnectionVerificationXo
            //Assert.IsInstanceOfType<IqConnectionVerificationXo> (instance, "variable 'instance' is a IqConnectionVerificationXo");
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

    }

}
