/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing MavenAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MavenAttributesTests
    {
        // TODO uncomment below to declare an instance variable for MavenAttributes
        //private MavenAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MavenAttributes
            //instance = new MavenAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MavenAttributes
        /// </summary>
        [Test]
        public void MavenAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MavenAttributes
            //Assert.IsInstanceOfType<MavenAttributes> (instance, "variable 'instance' is a MavenAttributes");
        }


        /// <summary>
        /// Test the property 'VersionPolicy'
        /// </summary>
        [Test]
        public void VersionPolicyTest()
        {
            // TODO unit test for the property 'VersionPolicy'
        }
        /// <summary>
        /// Test the property 'LayoutPolicy'
        /// </summary>
        [Test]
        public void LayoutPolicyTest()
        {
            // TODO unit test for the property 'LayoutPolicy'
        }

    }

}
