/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing NegativeCacheAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NegativeCacheAttributesTests
    {
        // TODO uncomment below to declare an instance variable for NegativeCacheAttributes
        //private NegativeCacheAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NegativeCacheAttributes
            //instance = new NegativeCacheAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NegativeCacheAttributes
        /// </summary>
        [Test]
        public void NegativeCacheAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NegativeCacheAttributes
            //Assert.IsInstanceOfType<NegativeCacheAttributes> (instance, "variable 'instance' is a NegativeCacheAttributes");
        }


        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'TimeToLive'
        /// </summary>
        [Test]
        public void TimeToLiveTest()
        {
            // TODO unit test for the property 'TimeToLive'
        }

    }

}
