/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing PageComponentXO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PageComponentXOTests
    {
        // TODO uncomment below to declare an instance variable for PageComponentXO
        //private PageComponentXO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PageComponentXO
            //instance = new PageComponentXO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PageComponentXO
        /// </summary>
        [Test]
        public void PageComponentXOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PageComponentXO
            //Assert.IsInstanceOfType<PageComponentXO> (instance, "variable 'instance' is a PageComponentXO");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'ContinuationToken'
        /// </summary>
        [Test]
        public void ContinuationTokenTest()
        {
            // TODO unit test for the property 'ContinuationToken'
        }

    }

}
