/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ProxyAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProxyAttributesTests
    {
        // TODO uncomment below to declare an instance variable for ProxyAttributes
        //private ProxyAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProxyAttributes
            //instance = new ProxyAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProxyAttributes
        /// </summary>
        [Test]
        public void ProxyAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProxyAttributes
            //Assert.IsInstanceOfType<ProxyAttributes> (instance, "variable 'instance' is a ProxyAttributes");
        }


        /// <summary>
        /// Test the property 'RemoteUrl'
        /// </summary>
        [Test]
        public void RemoteUrlTest()
        {
            // TODO unit test for the property 'RemoteUrl'
        }
        /// <summary>
        /// Test the property 'ContentMaxAge'
        /// </summary>
        [Test]
        public void ContentMaxAgeTest()
        {
            // TODO unit test for the property 'ContentMaxAge'
        }
        /// <summary>
        /// Test the property 'MetadataMaxAge'
        /// </summary>
        [Test]
        public void MetadataMaxAgeTest()
        {
            // TODO unit test for the property 'MetadataMaxAge'
        }

    }

}
