/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing RawAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RawAttributesTests
    {
        // TODO uncomment below to declare an instance variable for RawAttributes
        //private RawAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RawAttributes
            //instance = new RawAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RawAttributes
        /// </summary>
        [Test]
        public void RawAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RawAttributes
            //Assert.IsInstanceOfType<RawAttributes> (instance, "variable 'instance' is a RawAttributes");
        }


        /// <summary>
        /// Test the property 'ContentDisposition'
        /// </summary>
        [Test]
        public void ContentDispositionTest()
        {
            // TODO unit test for the property 'ContentDisposition'
        }

    }

}
