/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ReadOnlyState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReadOnlyStateTests
    {
        // TODO uncomment below to declare an instance variable for ReadOnlyState
        //private ReadOnlyState instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReadOnlyState
            //instance = new ReadOnlyState();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReadOnlyState
        /// </summary>
        [Test]
        public void ReadOnlyStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReadOnlyState
            //Assert.IsInstanceOfType<ReadOnlyState> (instance, "variable 'instance' is a ReadOnlyState");
        }


        /// <summary>
        /// Test the property 'SystemInitiated'
        /// </summary>
        [Test]
        public void SystemInitiatedTest()
        {
            // TODO unit test for the property 'SystemInitiated'
        }
        /// <summary>
        /// Test the property 'SummaryReason'
        /// </summary>
        [Test]
        public void SummaryReasonTest()
        {
            // TODO unit test for the property 'SummaryReason'
        }
        /// <summary>
        /// Test the property 'Frozen'
        /// </summary>
        [Test]
        public void FrozenTest()
        {
            // TODO unit test for the property 'Frozen'
        }

    }

}
