/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RequestTests
    {
        // TODO uncomment below to declare an instance variable for Request
        //private Request instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Request
            //instance = new Request();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Request
        /// </summary>
        [Test]
        public void RequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Request
            //Assert.IsInstanceOfType<Request> (instance, "variable 'instance' is a Request");
        }


        /// <summary>
        /// Test the property 'SystemInformation'
        /// </summary>
        [Test]
        public void SystemInformationTest()
        {
            // TODO unit test for the property 'SystemInformation'
        }
        /// <summary>
        /// Test the property 'ThreadDump'
        /// </summary>
        [Test]
        public void ThreadDumpTest()
        {
            // TODO unit test for the property 'ThreadDump'
        }
        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Test]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }
        /// <summary>
        /// Test the property 'Configuration'
        /// </summary>
        [Test]
        public void ConfigurationTest()
        {
            // TODO unit test for the property 'Configuration'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'Log'
        /// </summary>
        [Test]
        public void LogTest()
        {
            // TODO unit test for the property 'Log'
        }
        /// <summary>
        /// Test the property 'TaskLog'
        /// </summary>
        [Test]
        public void TaskLogTest()
        {
            // TODO unit test for the property 'TaskLog'
        }
        /// <summary>
        /// Test the property 'AuditLog'
        /// </summary>
        [Test]
        public void AuditLogTest()
        {
            // TODO unit test for the property 'AuditLog'
        }
        /// <summary>
        /// Test the property 'Jmx'
        /// </summary>
        [Test]
        public void JmxTest()
        {
            // TODO unit test for the property 'Jmx'
        }
        /// <summary>
        /// Test the property 'LimitFileSizes'
        /// </summary>
        [Test]
        public void LimitFileSizesTest()
        {
            // TODO unit test for the property 'LimitFileSizes'
        }
        /// <summary>
        /// Test the property 'LimitZipSize'
        /// </summary>
        [Test]
        public void LimitZipSizeTest()
        {
            // TODO unit test for the property 'LimitZipSize'
        }

    }

}
