/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing S3BlobStoreApiAdvancedBucketConnection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class S3BlobStoreApiAdvancedBucketConnectionTests
    {
        // TODO uncomment below to declare an instance variable for S3BlobStoreApiAdvancedBucketConnection
        //private S3BlobStoreApiAdvancedBucketConnection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of S3BlobStoreApiAdvancedBucketConnection
            //instance = new S3BlobStoreApiAdvancedBucketConnection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of S3BlobStoreApiAdvancedBucketConnection
        /// </summary>
        [Test]
        public void S3BlobStoreApiAdvancedBucketConnectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" S3BlobStoreApiAdvancedBucketConnection
            //Assert.IsInstanceOfType<S3BlobStoreApiAdvancedBucketConnection> (instance, "variable 'instance' is a S3BlobStoreApiAdvancedBucketConnection");
        }


        /// <summary>
        /// Test the property 'Endpoint'
        /// </summary>
        [Test]
        public void EndpointTest()
        {
            // TODO unit test for the property 'Endpoint'
        }
        /// <summary>
        /// Test the property 'SignerType'
        /// </summary>
        [Test]
        public void SignerTypeTest()
        {
            // TODO unit test for the property 'SignerType'
        }
        /// <summary>
        /// Test the property 'ForcePathStyle'
        /// </summary>
        [Test]
        public void ForcePathStyleTest()
        {
            // TODO unit test for the property 'ForcePathStyle'
        }

    }

}
