/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing S3BlobStoreApiBucketSecurity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class S3BlobStoreApiBucketSecurityTests
    {
        // TODO uncomment below to declare an instance variable for S3BlobStoreApiBucketSecurity
        //private S3BlobStoreApiBucketSecurity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of S3BlobStoreApiBucketSecurity
            //instance = new S3BlobStoreApiBucketSecurity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of S3BlobStoreApiBucketSecurity
        /// </summary>
        [Test]
        public void S3BlobStoreApiBucketSecurityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" S3BlobStoreApiBucketSecurity
            //Assert.IsInstanceOfType<S3BlobStoreApiBucketSecurity> (instance, "variable 'instance' is a S3BlobStoreApiBucketSecurity");
        }


        /// <summary>
        /// Test the property 'AccessKeyId'
        /// </summary>
        [Test]
        public void AccessKeyIdTest()
        {
            // TODO unit test for the property 'AccessKeyId'
        }
        /// <summary>
        /// Test the property 'SecretAccessKey'
        /// </summary>
        [Test]
        public void SecretAccessKeyTest()
        {
            // TODO unit test for the property 'SecretAccessKey'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'SessionToken'
        /// </summary>
        [Test]
        public void SessionTokenTest()
        {
            // TODO unit test for the property 'SessionToken'
        }

    }

}
