/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing S3BlobStoreApiBucketConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class S3BlobStoreApiBucketConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for S3BlobStoreApiBucketConfiguration
        //private S3BlobStoreApiBucketConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of S3BlobStoreApiBucketConfiguration
            //instance = new S3BlobStoreApiBucketConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of S3BlobStoreApiBucketConfiguration
        /// </summary>
        [Test]
        public void S3BlobStoreApiBucketConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" S3BlobStoreApiBucketConfiguration
            //Assert.IsInstanceOfType<S3BlobStoreApiBucketConfiguration> (instance, "variable 'instance' is a S3BlobStoreApiBucketConfiguration");
        }


        /// <summary>
        /// Test the property 'Bucket'
        /// </summary>
        [Test]
        public void BucketTest()
        {
            // TODO unit test for the property 'Bucket'
        }
        /// <summary>
        /// Test the property 'Encryption'
        /// </summary>
        [Test]
        public void EncryptionTest()
        {
            // TODO unit test for the property 'Encryption'
        }
        /// <summary>
        /// Test the property 'BucketSecurity'
        /// </summary>
        [Test]
        public void BucketSecurityTest()
        {
            // TODO unit test for the property 'BucketSecurity'
        }
        /// <summary>
        /// Test the property 'AdvancedBucketConnection'
        /// </summary>
        [Test]
        public void AdvancedBucketConnectionTest()
        {
            // TODO unit test for the property 'AdvancedBucketConnection'
        }

    }

}
