/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing S3BlobStoreApiEncryption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class S3BlobStoreApiEncryptionTests
    {
        // TODO uncomment below to declare an instance variable for S3BlobStoreApiEncryption
        //private S3BlobStoreApiEncryption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of S3BlobStoreApiEncryption
            //instance = new S3BlobStoreApiEncryption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of S3BlobStoreApiEncryption
        /// </summary>
        [Test]
        public void S3BlobStoreApiEncryptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" S3BlobStoreApiEncryption
            //Assert.IsInstanceOfType<S3BlobStoreApiEncryption> (instance, "variable 'instance' is a S3BlobStoreApiEncryption");
        }


        /// <summary>
        /// Test the property 'EncryptionType'
        /// </summary>
        [Test]
        public void EncryptionTypeTest()
        {
            // TODO unit test for the property 'EncryptionType'
        }
        /// <summary>
        /// Test the property 'EncryptionKey'
        /// </summary>
        [Test]
        public void EncryptionKeyTest()
        {
            // TODO unit test for the property 'EncryptionKey'
        }

    }

}
