/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing StackTraceElement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StackTraceElementTests
    {
        // TODO uncomment below to declare an instance variable for StackTraceElement
        //private StackTraceElement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StackTraceElement
            //instance = new StackTraceElement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StackTraceElement
        /// </summary>
        [Test]
        public void StackTraceElementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StackTraceElement
            //Assert.IsInstanceOfType<StackTraceElement> (instance, "variable 'instance' is a StackTraceElement");
        }


        /// <summary>
        /// Test the property 'MethodName'
        /// </summary>
        [Test]
        public void MethodNameTest()
        {
            // TODO unit test for the property 'MethodName'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'LineNumber'
        /// </summary>
        [Test]
        public void LineNumberTest()
        {
            // TODO unit test for the property 'LineNumber'
        }
        /// <summary>
        /// Test the property 'ClassName'
        /// </summary>
        [Test]
        public void ClassNameTest()
        {
            // TODO unit test for the property 'ClassName'
        }
        /// <summary>
        /// Test the property 'NativeMethod'
        /// </summary>
        [Test]
        public void NativeMethodTest()
        {
            // TODO unit test for the property 'NativeMethod'
        }

    }

}
