/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing TaskXO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskXOTests
    {
        // TODO uncomment below to declare an instance variable for TaskXO
        //private TaskXO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskXO
            //instance = new TaskXO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskXO
        /// </summary>
        [Test]
        public void TaskXOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskXO
            //Assert.IsInstanceOfType<TaskXO> (instance, "variable 'instance' is a TaskXO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'CurrentState'
        /// </summary>
        [Test]
        public void CurrentStateTest()
        {
            // TODO unit test for the property 'CurrentState'
        }
        /// <summary>
        /// Test the property 'LastRunResult'
        /// </summary>
        [Test]
        public void LastRunResultTest()
        {
            // TODO unit test for the property 'LastRunResult'
        }
        /// <summary>
        /// Test the property 'NextRun'
        /// </summary>
        [Test]
        public void NextRunTest()
        {
            // TODO unit test for the property 'NextRun'
        }
        /// <summary>
        /// Test the property 'LastRun'
        /// </summary>
        [Test]
        public void LastRunTest()
        {
            // TODO unit test for the property 'LastRun'
        }

    }

}
