/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing Throwable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ThrowableTests
    {
        // TODO uncomment below to declare an instance variable for Throwable
        //private Throwable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Throwable
            //instance = new Throwable();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Throwable
        /// </summary>
        [Test]
        public void ThrowableInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Throwable
            //Assert.IsInstanceOfType<Throwable> (instance, "variable 'instance' is a Throwable");
        }


        /// <summary>
        /// Test the property 'Cause'
        /// </summary>
        [Test]
        public void CauseTest()
        {
            // TODO unit test for the property 'Cause'
        }
        /// <summary>
        /// Test the property 'StackTrace'
        /// </summary>
        [Test]
        public void StackTraceTest()
        {
            // TODO unit test for the property 'StackTrace'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'LocalizedMessage'
        /// </summary>
        [Test]
        public void LocalizedMessageTest()
        {
            // TODO unit test for the property 'LocalizedMessage'
        }
        /// <summary>
        /// Test the property 'Suppressed'
        /// </summary>
        [Test]
        public void SuppressedTest()
        {
            // TODO unit test for the property 'Suppressed'
        }

    }

}
