/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing UpdateLdapServerXo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateLdapServerXoTests
    {
        // TODO uncomment below to declare an instance variable for UpdateLdapServerXo
        //private UpdateLdapServerXo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateLdapServerXo
            //instance = new UpdateLdapServerXo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateLdapServerXo
        /// </summary>
        [Test]
        public void UpdateLdapServerXoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateLdapServerXo
            //Assert.IsInstanceOfType<UpdateLdapServerXo> (instance, "variable 'instance' is a UpdateLdapServerXo");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Protocol'
        /// </summary>
        [Test]
        public void ProtocolTest()
        {
            // TODO unit test for the property 'Protocol'
        }
        /// <summary>
        /// Test the property 'UseTrustStore'
        /// </summary>
        [Test]
        public void UseTrustStoreTest()
        {
            // TODO unit test for the property 'UseTrustStore'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'SearchBase'
        /// </summary>
        [Test]
        public void SearchBaseTest()
        {
            // TODO unit test for the property 'SearchBase'
        }
        /// <summary>
        /// Test the property 'AuthScheme'
        /// </summary>
        [Test]
        public void AuthSchemeTest()
        {
            // TODO unit test for the property 'AuthScheme'
        }
        /// <summary>
        /// Test the property 'AuthRealm'
        /// </summary>
        [Test]
        public void AuthRealmTest()
        {
            // TODO unit test for the property 'AuthRealm'
        }
        /// <summary>
        /// Test the property 'AuthUsername'
        /// </summary>
        [Test]
        public void AuthUsernameTest()
        {
            // TODO unit test for the property 'AuthUsername'
        }
        /// <summary>
        /// Test the property 'ConnectionTimeoutSeconds'
        /// </summary>
        [Test]
        public void ConnectionTimeoutSecondsTest()
        {
            // TODO unit test for the property 'ConnectionTimeoutSeconds'
        }
        /// <summary>
        /// Test the property 'ConnectionRetryDelaySeconds'
        /// </summary>
        [Test]
        public void ConnectionRetryDelaySecondsTest()
        {
            // TODO unit test for the property 'ConnectionRetryDelaySeconds'
        }
        /// <summary>
        /// Test the property 'MaxIncidentsCount'
        /// </summary>
        [Test]
        public void MaxIncidentsCountTest()
        {
            // TODO unit test for the property 'MaxIncidentsCount'
        }
        /// <summary>
        /// Test the property 'UserBaseDn'
        /// </summary>
        [Test]
        public void UserBaseDnTest()
        {
            // TODO unit test for the property 'UserBaseDn'
        }
        /// <summary>
        /// Test the property 'UserSubtree'
        /// </summary>
        [Test]
        public void UserSubtreeTest()
        {
            // TODO unit test for the property 'UserSubtree'
        }
        /// <summary>
        /// Test the property 'UserObjectClass'
        /// </summary>
        [Test]
        public void UserObjectClassTest()
        {
            // TODO unit test for the property 'UserObjectClass'
        }
        /// <summary>
        /// Test the property 'UserLdapFilter'
        /// </summary>
        [Test]
        public void UserLdapFilterTest()
        {
            // TODO unit test for the property 'UserLdapFilter'
        }
        /// <summary>
        /// Test the property 'UserIdAttribute'
        /// </summary>
        [Test]
        public void UserIdAttributeTest()
        {
            // TODO unit test for the property 'UserIdAttribute'
        }
        /// <summary>
        /// Test the property 'UserRealNameAttribute'
        /// </summary>
        [Test]
        public void UserRealNameAttributeTest()
        {
            // TODO unit test for the property 'UserRealNameAttribute'
        }
        /// <summary>
        /// Test the property 'UserEmailAddressAttribute'
        /// </summary>
        [Test]
        public void UserEmailAddressAttributeTest()
        {
            // TODO unit test for the property 'UserEmailAddressAttribute'
        }
        /// <summary>
        /// Test the property 'UserPasswordAttribute'
        /// </summary>
        [Test]
        public void UserPasswordAttributeTest()
        {
            // TODO unit test for the property 'UserPasswordAttribute'
        }
        /// <summary>
        /// Test the property 'LdapGroupsAsRoles'
        /// </summary>
        [Test]
        public void LdapGroupsAsRolesTest()
        {
            // TODO unit test for the property 'LdapGroupsAsRoles'
        }
        /// <summary>
        /// Test the property 'GroupType'
        /// </summary>
        [Test]
        public void GroupTypeTest()
        {
            // TODO unit test for the property 'GroupType'
        }
        /// <summary>
        /// Test the property 'GroupBaseDn'
        /// </summary>
        [Test]
        public void GroupBaseDnTest()
        {
            // TODO unit test for the property 'GroupBaseDn'
        }
        /// <summary>
        /// Test the property 'GroupSubtree'
        /// </summary>
        [Test]
        public void GroupSubtreeTest()
        {
            // TODO unit test for the property 'GroupSubtree'
        }
        /// <summary>
        /// Test the property 'GroupObjectClass'
        /// </summary>
        [Test]
        public void GroupObjectClassTest()
        {
            // TODO unit test for the property 'GroupObjectClass'
        }
        /// <summary>
        /// Test the property 'GroupIdAttribute'
        /// </summary>
        [Test]
        public void GroupIdAttributeTest()
        {
            // TODO unit test for the property 'GroupIdAttribute'
        }
        /// <summary>
        /// Test the property 'GroupMemberAttribute'
        /// </summary>
        [Test]
        public void GroupMemberAttributeTest()
        {
            // TODO unit test for the property 'GroupMemberAttribute'
        }
        /// <summary>
        /// Test the property 'GroupMemberFormat'
        /// </summary>
        [Test]
        public void GroupMemberFormatTest()
        {
            // TODO unit test for the property 'GroupMemberFormat'
        }
        /// <summary>
        /// Test the property 'UserMemberOfAttribute'
        /// </summary>
        [Test]
        public void UserMemberOfAttributeTest()
        {
            // TODO unit test for the property 'UserMemberOfAttribute'
        }
        /// <summary>
        /// Test the property 'AuthPassword'
        /// </summary>
        [Test]
        public void AuthPasswordTest()
        {
            // TODO unit test for the property 'AuthPassword'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
