/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing UploadFieldDefinitionXO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UploadFieldDefinitionXOTests
    {
        // TODO uncomment below to declare an instance variable for UploadFieldDefinitionXO
        //private UploadFieldDefinitionXO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UploadFieldDefinitionXO
            //instance = new UploadFieldDefinitionXO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UploadFieldDefinitionXO
        /// </summary>
        [Test]
        public void UploadFieldDefinitionXOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UploadFieldDefinitionXO
            //Assert.IsInstanceOfType<UploadFieldDefinitionXO> (instance, "variable 'instance' is a UploadFieldDefinitionXO");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Optional'
        /// </summary>
        [Test]
        public void OptionalTest()
        {
            // TODO unit test for the property 'Optional'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

    }

}
