/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing UploadDefinitionXO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UploadDefinitionXOTests
    {
        // TODO uncomment below to declare an instance variable for UploadDefinitionXO
        //private UploadDefinitionXO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UploadDefinitionXO
            //instance = new UploadDefinitionXO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UploadDefinitionXO
        /// </summary>
        [Test]
        public void UploadDefinitionXOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UploadDefinitionXO
            //Assert.IsInstanceOfType<UploadDefinitionXO> (instance, "variable 'instance' is a UploadDefinitionXO");
        }


        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'MultipleUpload'
        /// </summary>
        [Test]
        public void MultipleUploadTest()
        {
            // TODO unit test for the property 'MultipleUpload'
        }
        /// <summary>
        /// Test the property 'ComponentFields'
        /// </summary>
        [Test]
        public void ComponentFieldsTest()
        {
            // TODO unit test for the property 'ComponentFields'
        }
        /// <summary>
        /// Test the property 'AssetFields'
        /// </summary>
        [Test]
        public void AssetFieldsTest()
        {
            // TODO unit test for the property 'AssetFields'
        }

    }

}
