/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;
using SonaTypeNexusRepoApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing YumAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class YumAttributesTests
    {
        // TODO uncomment below to declare an instance variable for YumAttributes
        //private YumAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of YumAttributes
            //instance = new YumAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of YumAttributes
        /// </summary>
        [Test]
        public void YumAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" YumAttributes
            //Assert.IsInstanceOfType<YumAttributes> (instance, "variable 'instance' is a YumAttributes");
        }


        /// <summary>
        /// Test the property 'RepodataDepth'
        /// </summary>
        [Test]
        public void RepodataDepthTest()
        {
            // TODO unit test for the property 'RepodataDepth'
        }
        /// <summary>
        /// Test the property 'DeployPolicy'
        /// </summary>
        [Test]
        public void DeployPolicyTest()
        {
            // TODO unit test for the property 'DeployPolicy'
        }

    }

}
