/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SonaTypeNexusRepoApi.Client.SwaggerDateConverter;

namespace SonaTypeNexusRepoApi.Model
{
    /// <summary>
    /// HttpClientConnectionAttributes
    /// </summary>
    [DataContract]
    public partial class HttpClientConnectionAttributes :  IEquatable<HttpClientConnectionAttributes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpClientConnectionAttributes" /> class.
        /// </summary>
        /// <param name="retries">Total retries if the initial connection attempt suffers a timeout.</param>
        /// <param name="userAgentSuffix">Custom fragment to append to User-Agent header in HTTP requests.</param>
        /// <param name="timeout">Seconds to wait for activity before stopping and retrying the connection.</param>
        /// <param name="enableCircularRedirects">Whether to enable redirects to the same location (may be required by some servers).</param>
        /// <param name="enableCookies">Whether to allow cookies to be stored and used.</param>
        public HttpClientConnectionAttributes(int? retries = default(int?), string userAgentSuffix = default(string), int? timeout = default(int?), bool? enableCircularRedirects = default(bool?), bool? enableCookies = default(bool?))
        {
            this.Retries = retries;
            this.UserAgentSuffix = userAgentSuffix;
            this.Timeout = timeout;
            this.EnableCircularRedirects = enableCircularRedirects;
            this.EnableCookies = enableCookies;
        }
        
        /// <summary>
        /// Total retries if the initial connection attempt suffers a timeout
        /// </summary>
        /// <value>Total retries if the initial connection attempt suffers a timeout</value>
        [DataMember(Name="retries", EmitDefaultValue=false)]
        public int? Retries { get; set; }

        /// <summary>
        /// Custom fragment to append to User-Agent header in HTTP requests
        /// </summary>
        /// <value>Custom fragment to append to User-Agent header in HTTP requests</value>
        [DataMember(Name="userAgentSuffix", EmitDefaultValue=false)]
        public string UserAgentSuffix { get; set; }

        /// <summary>
        /// Seconds to wait for activity before stopping and retrying the connection
        /// </summary>
        /// <value>Seconds to wait for activity before stopping and retrying the connection</value>
        [DataMember(Name="timeout", EmitDefaultValue=false)]
        public int? Timeout { get; set; }

        /// <summary>
        /// Whether to enable redirects to the same location (may be required by some servers)
        /// </summary>
        /// <value>Whether to enable redirects to the same location (may be required by some servers)</value>
        [DataMember(Name="enableCircularRedirects", EmitDefaultValue=false)]
        public bool? EnableCircularRedirects { get; set; }

        /// <summary>
        /// Whether to allow cookies to be stored and used
        /// </summary>
        /// <value>Whether to allow cookies to be stored and used</value>
        [DataMember(Name="enableCookies", EmitDefaultValue=false)]
        public bool? EnableCookies { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpClientConnectionAttributes {\n");
            sb.Append("  Retries: ").Append(Retries).Append("\n");
            sb.Append("  UserAgentSuffix: ").Append(UserAgentSuffix).Append("\n");
            sb.Append("  Timeout: ").Append(Timeout).Append("\n");
            sb.Append("  EnableCircularRedirects: ").Append(EnableCircularRedirects).Append("\n");
            sb.Append("  EnableCookies: ").Append(EnableCookies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HttpClientConnectionAttributes);
        }

        /// <summary>
        /// Returns true if HttpClientConnectionAttributes instances are equal
        /// </summary>
        /// <param name="input">Instance of HttpClientConnectionAttributes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpClientConnectionAttributes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Retries == input.Retries ||
                    (this.Retries != null &&
                    this.Retries.Equals(input.Retries))
                ) && 
                (
                    this.UserAgentSuffix == input.UserAgentSuffix ||
                    (this.UserAgentSuffix != null &&
                    this.UserAgentSuffix.Equals(input.UserAgentSuffix))
                ) && 
                (
                    this.Timeout == input.Timeout ||
                    (this.Timeout != null &&
                    this.Timeout.Equals(input.Timeout))
                ) && 
                (
                    this.EnableCircularRedirects == input.EnableCircularRedirects ||
                    (this.EnableCircularRedirects != null &&
                    this.EnableCircularRedirects.Equals(input.EnableCircularRedirects))
                ) && 
                (
                    this.EnableCookies == input.EnableCookies ||
                    (this.EnableCookies != null &&
                    this.EnableCookies.Equals(input.EnableCookies))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Retries != null)
                    hashCode = hashCode * 59 + this.Retries.GetHashCode();
                if (this.UserAgentSuffix != null)
                    hashCode = hashCode * 59 + this.UserAgentSuffix.GetHashCode();
                if (this.Timeout != null)
                    hashCode = hashCode * 59 + this.Timeout.GetHashCode();
                if (this.EnableCircularRedirects != null)
                    hashCode = hashCode * 59 + this.EnableCircularRedirects.GetHashCode();
                if (this.EnableCookies != null)
                    hashCode = hashCode * 59 + this.EnableCookies.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Retries (int?) maximum
            if(this.Retries > (int?)10)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Retries, must be a value less than or equal to 10.", new [] { "Retries" });
            }

            // Retries (int?) minimum
            if(this.Retries < (int?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Retries, must be a value greater than or equal to 0.", new [] { "Retries" });
            }

            // Timeout (int?) maximum
            if(this.Timeout > (int?)3600)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Timeout, must be a value less than or equal to 3600.", new [] { "Timeout" });
            }

            // Timeout (int?) minimum
            if(this.Timeout < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Timeout, must be a value greater than or equal to 1.", new [] { "Timeout" });
            }

            yield break;
        }
    }

}
