/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SonaTypeNexusRepoApi.Client.SwaggerDateConverter;

namespace SonaTypeNexusRepoApi.Model
{
    /// <summary>
    /// NugetAttributes
    /// </summary>
    [DataContract]
    public partial class NugetAttributes :  IEquatable<NugetAttributes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NugetAttributes" /> class.
        /// </summary>
        /// <param name="queryCacheItemMaxAge">How long to cache query results from the proxied repository (in seconds).</param>
        public NugetAttributes(int? queryCacheItemMaxAge = default(int?))
        {
            this.QueryCacheItemMaxAge = queryCacheItemMaxAge;
        }
        
        /// <summary>
        /// How long to cache query results from the proxied repository (in seconds)
        /// </summary>
        /// <value>How long to cache query results from the proxied repository (in seconds)</value>
        [DataMember(Name="queryCacheItemMaxAge", EmitDefaultValue=false)]
        public int? QueryCacheItemMaxAge { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NugetAttributes {\n");
            sb.Append("  QueryCacheItemMaxAge: ").Append(QueryCacheItemMaxAge).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NugetAttributes);
        }

        /// <summary>
        /// Returns true if NugetAttributes instances are equal
        /// </summary>
        /// <param name="input">Instance of NugetAttributes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NugetAttributes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QueryCacheItemMaxAge == input.QueryCacheItemMaxAge ||
                    (this.QueryCacheItemMaxAge != null &&
                    this.QueryCacheItemMaxAge.Equals(input.QueryCacheItemMaxAge))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QueryCacheItemMaxAge != null)
                    hashCode = hashCode * 59 + this.QueryCacheItemMaxAge.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
