/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing BlobStoreApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BlobStoreApiTests
    {
        private BlobStoreApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BlobStoreApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlobStoreApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BlobStoreApi
            //Assert.IsInstanceOfType(typeof(BlobStoreApi), instance, "instance is a BlobStoreApi");
        }

        
        /// <summary>
        /// Test CreateBlobStore
        /// </summary>
        [Test]
        public void CreateBlobStoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //S3BlobStoreApiModel body = null;
            //instance.CreateBlobStore(body);
            
        }
        
        /// <summary>
        /// Test CreateFileBlobStore
        /// </summary>
        [Test]
        public void CreateFileBlobStoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FileBlobStoreApiCreateRequest body = null;
            //instance.CreateFileBlobStore(body);
            
        }
        
        /// <summary>
        /// Test DeleteBlobStore
        /// </summary>
        [Test]
        public void DeleteBlobStoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //instance.DeleteBlobStore(name);
            
        }
        
        /// <summary>
        /// Test GetBlobStore
        /// </summary>
        [Test]
        public void GetBlobStoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //instance.GetBlobStore(name);
            
        }
        
        /// <summary>
        /// Test GetFileBlobStoreConfiguration
        /// </summary>
        [Test]
        public void GetFileBlobStoreConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //var response = instance.GetFileBlobStoreConfiguration(name);
            //Assert.IsInstanceOf<FileBlobStoreApiModel> (response, "response is FileBlobStoreApiModel");
        }
        
        /// <summary>
        /// Test ListBlobStores
        /// </summary>
        [Test]
        public void ListBlobStoresTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListBlobStores();
            //Assert.IsInstanceOf<List<GenericBlobStoreApiResponse>> (response, "response is List<GenericBlobStoreApiResponse>");
        }
        
        /// <summary>
        /// Test QuotaStatus
        /// </summary>
        [Test]
        public void QuotaStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //var response = instance.QuotaStatus(name);
            //Assert.IsInstanceOf<BlobStoreQuotaResultXO> (response, "response is BlobStoreQuotaResultXO");
        }
        
        /// <summary>
        /// Test UpdateBlobStore
        /// </summary>
        [Test]
        public void UpdateBlobStoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //S3BlobStoreApiModel body = null;
            //instance.UpdateBlobStore(name, body);
            
        }
        
        /// <summary>
        /// Test UpdateFileBlobStore
        /// </summary>
        [Test]
        public void UpdateFileBlobStoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //FileBlobStoreApiUpdateRequest body = null;
            //instance.UpdateFileBlobStore(name, body);
            
        }
        
    }

}
