/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ContentSelectorsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ContentSelectorsApiTests
    {
        private ContentSelectorsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ContentSelectorsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContentSelectorsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ContentSelectorsApi
            //Assert.IsInstanceOfType(typeof(ContentSelectorsApi), instance, "instance is a ContentSelectorsApi");
        }

        
        /// <summary>
        /// Test CreateContentSelector
        /// </summary>
        [Test]
        public void CreateContentSelectorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ContentSelectorApiCreateRequest body = null;
            //instance.CreateContentSelector(body);
            
        }
        
        /// <summary>
        /// Test DeleteContentSelector
        /// </summary>
        [Test]
        public void DeleteContentSelectorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //instance.DeleteContentSelector(name);
            
        }
        
        /// <summary>
        /// Test GetContentSelector
        /// </summary>
        [Test]
        public void GetContentSelectorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //var response = instance.GetContentSelector(name);
            //Assert.IsInstanceOf<ContentSelectorApiResponse> (response, "response is ContentSelectorApiResponse");
        }
        
        /// <summary>
        /// Test GetContentSelectors
        /// </summary>
        [Test]
        public void GetContentSelectorsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetContentSelectors();
            //Assert.IsInstanceOf<List<ContentSelectorApiResponse>> (response, "response is List<ContentSelectorApiResponse>");
        }
        
        /// <summary>
        /// Test UpdateContentSelector
        /// </summary>
        [Test]
        public void UpdateContentSelectorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //ContentSelectorApiUpdateRequest body = null;
            //instance.UpdateContentSelector(name, body);
            
        }
        
    }

}
