/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing EmailApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EmailApiTests
    {
        private EmailApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EmailApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmailApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EmailApi
            //Assert.IsInstanceOfType(typeof(EmailApi), instance, "instance is a EmailApi");
        }

        
        /// <summary>
        /// Test DeleteEmailConfiguration
        /// </summary>
        [Test]
        public void DeleteEmailConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DeleteEmailConfiguration();
            
        }
        
        /// <summary>
        /// Test GetEmailConfiguration
        /// </summary>
        [Test]
        public void GetEmailConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetEmailConfiguration();
            //Assert.IsInstanceOf<ApiEmailConfiguration> (response, "response is ApiEmailConfiguration");
        }
        
        /// <summary>
        /// Test SetEmailConfiguration
        /// </summary>
        [Test]
        public void SetEmailConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ApiEmailConfiguration body = null;
            //instance.SetEmailConfiguration(body);
            
        }
        
        /// <summary>
        /// Test TestEmailConfiguration
        /// </summary>
        [Test]
        public void TestEmailConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //var response = instance.TestEmailConfiguration(body);
            //Assert.IsInstanceOf<ApiEmailValidation> (response, "response is ApiEmailValidation");
        }
        
    }

}
