/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing FormatsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FormatsApiTests
    {
        private FormatsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FormatsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormatsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FormatsApi
            //Assert.IsInstanceOfType(typeof(FormatsApi), instance, "instance is a FormatsApi");
        }

        
        /// <summary>
        /// Test Get1
        /// </summary>
        [Test]
        public void Get1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string format = null;
            //var response = instance.Get1(format);
            //Assert.IsInstanceOf<UploadDefinitionXO> (response, "response is UploadDefinitionXO");
        }
        
        /// <summary>
        /// Test Get2
        /// </summary>
        [Test]
        public void Get2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Get2();
            //Assert.IsInstanceOf<List<UploadDefinitionXO>> (response, "response is List<UploadDefinitionXO>");
        }
        
    }

}
