/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing LifecycleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LifecycleApiTests
    {
        private LifecycleApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LifecycleApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LifecycleApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LifecycleApi
            //Assert.IsInstanceOfType(typeof(LifecycleApi), instance, "instance is a LifecycleApi");
        }

        
        /// <summary>
        /// Test Bounce
        /// </summary>
        [Test]
        public void BounceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //instance.Bounce(body);
            
        }
        
        /// <summary>
        /// Test GetPhase
        /// </summary>
        [Test]
        public void GetPhaseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetPhase();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SetPhase
        /// </summary>
        [Test]
        public void SetPhaseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //instance.SetPhase(body);
            
        }
        
    }

}
