/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ProductLicensingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProductLicensingApiTests
    {
        private ProductLicensingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProductLicensingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductLicensingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProductLicensingApi
            //Assert.IsInstanceOfType(typeof(ProductLicensingApi), instance, "instance is a ProductLicensingApi");
        }

        
        /// <summary>
        /// Test GetLicenseStatus
        /// </summary>
        [Test]
        public void GetLicenseStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetLicenseStatus();
            //Assert.IsInstanceOf<ApiLicenseDetailsXO> (response, "response is ApiLicenseDetailsXO");
        }
        
        /// <summary>
        /// Test RemoveLicense
        /// </summary>
        [Test]
        public void RemoveLicenseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.RemoveLicense();
            
        }
        
        /// <summary>
        /// Test SetLicense
        /// </summary>
        [Test]
        public void SetLicenseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InputStream body = null;
            //var response = instance.SetLicense(body);
            //Assert.IsInstanceOf<ApiLicenseDetailsXO> (response, "response is ApiLicenseDetailsXO");
        }
        
    }

}
