/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing ReadOnlyApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ReadOnlyApiTests
    {
        private ReadOnlyApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ReadOnlyApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReadOnlyApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ReadOnlyApi
            //Assert.IsInstanceOfType(typeof(ReadOnlyApi), instance, "instance is a ReadOnlyApi");
        }

        
        /// <summary>
        /// Test ForceRelease
        /// </summary>
        [Test]
        public void ForceReleaseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ForceRelease();
            
        }
        
        /// <summary>
        /// Test Freeze
        /// </summary>
        [Test]
        public void FreezeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.Freeze();
            
        }
        
        /// <summary>
        /// Test Get
        /// </summary>
        [Test]
        public void GetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Get();
            //Assert.IsInstanceOf<ReadOnlyState> (response, "response is ReadOnlyState");
        }
        
        /// <summary>
        /// Test Release
        /// </summary>
        [Test]
        public void ReleaseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.Release();
            
        }
        
    }

}
