/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing RepositoryManagementApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RepositoryManagementApiTests
    {
        private RepositoryManagementApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RepositoryManagementApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RepositoryManagementApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RepositoryManagementApi
            //Assert.IsInstanceOfType(typeof(RepositoryManagementApi), instance, "instance is a RepositoryManagementApi");
        }

        
        /// <summary>
        /// Test CreateRepository
        /// </summary>
        [Test]
        public void CreateRepositoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MavenGroupRepositoryApiRequest body = null;
            //instance.CreateRepository(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository1
        /// </summary>
        [Test]
        public void CreateRepository1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MavenHostedRepositoryApiRequest body = null;
            //instance.CreateRepository1(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository10
        /// </summary>
        [Test]
        public void CreateRepository10Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NugetProxyRepositoryApiRequest body = null;
            //instance.CreateRepository10(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository11
        /// </summary>
        [Test]
        public void CreateRepository11Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NpmGroupRepositoryApiRequest body = null;
            //instance.CreateRepository11(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository12
        /// </summary>
        [Test]
        public void CreateRepository12Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NpmHostedRepositoryApiRequest body = null;
            //instance.CreateRepository12(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository13
        /// </summary>
        [Test]
        public void CreateRepository13Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NpmProxyRepositoryApiRequest body = null;
            //instance.CreateRepository13(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository14
        /// </summary>
        [Test]
        public void CreateRepository14Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RubyGemsGroupRepositoryApiRequest body = null;
            //instance.CreateRepository14(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository15
        /// </summary>
        [Test]
        public void CreateRepository15Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RubyGemsHostedRepositoryApiRequest body = null;
            //instance.CreateRepository15(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository16
        /// </summary>
        [Test]
        public void CreateRepository16Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RubyGemsProxyRepositoryApiRequest body = null;
            //instance.CreateRepository16(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository17
        /// </summary>
        [Test]
        public void CreateRepository17Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AptHostedRepositoryApiRequest body = null;
            //instance.CreateRepository17(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository18
        /// </summary>
        [Test]
        public void CreateRepository18Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AptProxyRepositoryApiRequest body = null;
            //instance.CreateRepository18(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository19
        /// </summary>
        [Test]
        public void CreateRepository19Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CocoapodsProxyRepositoryApiRequest body = null;
            //instance.CreateRepository19(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository2
        /// </summary>
        [Test]
        public void CreateRepository2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MavenProxyRepositoryApiRequest body = null;
            //instance.CreateRepository2(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository20
        /// </summary>
        [Test]
        public void CreateRepository20Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GolangGroupRepositoryApiRequest body = null;
            //instance.CreateRepository20(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository21
        /// </summary>
        [Test]
        public void CreateRepository21Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GolangProxyRepositoryApiRequest body = null;
            //instance.CreateRepository21(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository22
        /// </summary>
        [Test]
        public void CreateRepository22Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PypiGroupRepositoryApiRequest body = null;
            //instance.CreateRepository22(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository23
        /// </summary>
        [Test]
        public void CreateRepository23Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PypiHostedRepositoryApiRequest body = null;
            //instance.CreateRepository23(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository24
        /// </summary>
        [Test]
        public void CreateRepository24Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PypiProxyRepositoryApiRequest body = null;
            //instance.CreateRepository24(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository25
        /// </summary>
        [Test]
        public void CreateRepository25Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConanProxyRepositoryApiRequest body = null;
            //instance.CreateRepository25(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository26
        /// </summary>
        [Test]
        public void CreateRepository26Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //P2ProxyRepositoryApiRequest body = null;
            //instance.CreateRepository26(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository27
        /// </summary>
        [Test]
        public void CreateRepository27Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RGroupRepositoryApiRequest body = null;
            //instance.CreateRepository27(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository28
        /// </summary>
        [Test]
        public void CreateRepository28Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RHostedRepositoryApiRequest body = null;
            //instance.CreateRepository28(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository29
        /// </summary>
        [Test]
        public void CreateRepository29Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RProxyRepositoryApiRequest body = null;
            //instance.CreateRepository29(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository3
        /// </summary>
        [Test]
        public void CreateRepository3Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RawGroupRepositoryApiRequest body = null;
            //instance.CreateRepository3(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository30
        /// </summary>
        [Test]
        public void CreateRepository30Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BowerGroupRepositoryApiRequest body = null;
            //instance.CreateRepository30(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository31
        /// </summary>
        [Test]
        public void CreateRepository31Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BowerHostedRepositoryApiRequest body = null;
            //instance.CreateRepository31(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository32
        /// </summary>
        [Test]
        public void CreateRepository32Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BowerProxyRepositoryApiRequest body = null;
            //instance.CreateRepository32(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository33
        /// </summary>
        [Test]
        public void CreateRepository33Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DockerGroupRepositoryApiRequest body = null;
            //instance.CreateRepository33(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository34
        /// </summary>
        [Test]
        public void CreateRepository34Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DockerHostedRepositoryApiRequest body = null;
            //instance.CreateRepository34(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository35
        /// </summary>
        [Test]
        public void CreateRepository35Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DockerProxyRepositoryApiRequest body = null;
            //instance.CreateRepository35(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository36
        /// </summary>
        [Test]
        public void CreateRepository36Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GitLfsHostedRepositoryApiRequest body = null;
            //instance.CreateRepository36(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository37
        /// </summary>
        [Test]
        public void CreateRepository37Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //YumGroupRepositoryApiRequest body = null;
            //instance.CreateRepository37(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository38
        /// </summary>
        [Test]
        public void CreateRepository38Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //YumHostedRepositoryApiRequest body = null;
            //instance.CreateRepository38(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository39
        /// </summary>
        [Test]
        public void CreateRepository39Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //YumProxyRepositoryApiRequest body = null;
            //instance.CreateRepository39(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository4
        /// </summary>
        [Test]
        public void CreateRepository4Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RawHostedRepositoryApiRequest body = null;
            //instance.CreateRepository4(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository5
        /// </summary>
        [Test]
        public void CreateRepository5Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RawProxyRepositoryApiRequest body = null;
            //instance.CreateRepository5(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository6
        /// </summary>
        [Test]
        public void CreateRepository6Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HelmHostedRepositoryApiRequest body = null;
            //instance.CreateRepository6(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository7
        /// </summary>
        [Test]
        public void CreateRepository7Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HelmProxyRepositoryApiRequest body = null;
            //instance.CreateRepository7(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository8
        /// </summary>
        [Test]
        public void CreateRepository8Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NugetGroupRepositoryApiRequest body = null;
            //instance.CreateRepository8(body);
            
        }
        
        /// <summary>
        /// Test CreateRepository9
        /// </summary>
        [Test]
        public void CreateRepository9Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NugetHostedRepositoryApiRequest body = null;
            //instance.CreateRepository9(body);
            
        }
        
        /// <summary>
        /// Test DeleteRepository
        /// </summary>
        [Test]
        public void DeleteRepositoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //instance.DeleteRepository(repositoryName);
            
        }
        
        /// <summary>
        /// Test DisableRepositoryHealthCheck
        /// </summary>
        [Test]
        public void DisableRepositoryHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //instance.DisableRepositoryHealthCheck(repositoryName);
            
        }
        
        /// <summary>
        /// Test EnableRepositoryHealthCheck
        /// </summary>
        [Test]
        public void EnableRepositoryHealthCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //instance.EnableRepositoryHealthCheck(repositoryName);
            
        }
        
        /// <summary>
        /// Test GetRepositories
        /// </summary>
        [Test]
        public void GetRepositoriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetRepositories();
            //Assert.IsInstanceOf<List<AbstractApiRepository>> (response, "response is List<AbstractApiRepository>");
        }
        
        /// <summary>
        /// Test InvalidateCache
        /// </summary>
        [Test]
        public void InvalidateCacheTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //instance.InvalidateCache(repositoryName);
            
        }
        
        /// <summary>
        /// Test RebuildIndex
        /// </summary>
        [Test]
        public void RebuildIndexTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //instance.RebuildIndex(repositoryName);
            
        }
        
        /// <summary>
        /// Test UpdateRepository
        /// </summary>
        [Test]
        public void UpdateRepositoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //MavenGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository1
        /// </summary>
        [Test]
        public void UpdateRepository1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //MavenHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository1(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository10
        /// </summary>
        [Test]
        public void UpdateRepository10Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //NugetProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository10(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository11
        /// </summary>
        [Test]
        public void UpdateRepository11Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //NpmGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository11(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository12
        /// </summary>
        [Test]
        public void UpdateRepository12Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //NpmHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository12(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository13
        /// </summary>
        [Test]
        public void UpdateRepository13Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //NpmProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository13(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository14
        /// </summary>
        [Test]
        public void UpdateRepository14Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RubyGemsGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository14(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository15
        /// </summary>
        [Test]
        public void UpdateRepository15Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RubyGemsHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository15(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository16
        /// </summary>
        [Test]
        public void UpdateRepository16Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RubyGemsProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository16(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository17
        /// </summary>
        [Test]
        public void UpdateRepository17Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //AptHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository17(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository18
        /// </summary>
        [Test]
        public void UpdateRepository18Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //AptProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository18(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository19
        /// </summary>
        [Test]
        public void UpdateRepository19Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //CocoapodsProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository19(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository2
        /// </summary>
        [Test]
        public void UpdateRepository2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //MavenProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository2(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository20
        /// </summary>
        [Test]
        public void UpdateRepository20Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //GolangGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository20(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository21
        /// </summary>
        [Test]
        public void UpdateRepository21Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //GolangProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository21(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository22
        /// </summary>
        [Test]
        public void UpdateRepository22Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //PypiGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository22(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository23
        /// </summary>
        [Test]
        public void UpdateRepository23Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //PypiHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository23(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository24
        /// </summary>
        [Test]
        public void UpdateRepository24Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //PypiProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository24(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository25
        /// </summary>
        [Test]
        public void UpdateRepository25Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //ConanProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository25(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository26
        /// </summary>
        [Test]
        public void UpdateRepository26Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //P2ProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository26(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository27
        /// </summary>
        [Test]
        public void UpdateRepository27Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository27(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository28
        /// </summary>
        [Test]
        public void UpdateRepository28Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository28(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository29
        /// </summary>
        [Test]
        public void UpdateRepository29Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository29(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository3
        /// </summary>
        [Test]
        public void UpdateRepository3Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RawGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository3(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository30
        /// </summary>
        [Test]
        public void UpdateRepository30Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //BowerGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository30(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository31
        /// </summary>
        [Test]
        public void UpdateRepository31Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //BowerHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository31(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository32
        /// </summary>
        [Test]
        public void UpdateRepository32Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //BowerProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository32(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository33
        /// </summary>
        [Test]
        public void UpdateRepository33Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //DockerGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository33(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository34
        /// </summary>
        [Test]
        public void UpdateRepository34Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //DockerHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository34(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository35
        /// </summary>
        [Test]
        public void UpdateRepository35Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //DockerProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository35(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository36
        /// </summary>
        [Test]
        public void UpdateRepository36Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //GitLfsHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository36(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository37
        /// </summary>
        [Test]
        public void UpdateRepository37Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //YumGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository37(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository38
        /// </summary>
        [Test]
        public void UpdateRepository38Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //YumHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository38(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository39
        /// </summary>
        [Test]
        public void UpdateRepository39Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //YumProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository39(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository4
        /// </summary>
        [Test]
        public void UpdateRepository4Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RawHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository4(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository5
        /// </summary>
        [Test]
        public void UpdateRepository5Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //RawProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository5(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository6
        /// </summary>
        [Test]
        public void UpdateRepository6Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //HelmHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository6(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository7
        /// </summary>
        [Test]
        public void UpdateRepository7Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //HelmProxyRepositoryApiRequest body = null;
            //instance.UpdateRepository7(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository8
        /// </summary>
        [Test]
        public void UpdateRepository8Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //NugetGroupRepositoryApiRequest body = null;
            //instance.UpdateRepository8(repositoryName, body);
            
        }
        
        /// <summary>
        /// Test UpdateRepository9
        /// </summary>
        [Test]
        public void UpdateRepository9Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string repositoryName = null;
            //NugetHostedRepositoryApiRequest body = null;
            //instance.UpdateRepository9(repositoryName, body);
            
        }
        
    }

}
