/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing RoutingRulesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RoutingRulesApiTests
    {
        private RoutingRulesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RoutingRulesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RoutingRulesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RoutingRulesApi
            //Assert.IsInstanceOfType(typeof(RoutingRulesApi), instance, "instance is a RoutingRulesApi");
        }

        
        /// <summary>
        /// Test CreateRoutingRule
        /// </summary>
        [Test]
        public void CreateRoutingRuleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RoutingRuleXO body = null;
            //instance.CreateRoutingRule(body);
            
        }
        
        /// <summary>
        /// Test DeleteRoutingRule
        /// </summary>
        [Test]
        public void DeleteRoutingRuleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //instance.DeleteRoutingRule(name);
            
        }
        
        /// <summary>
        /// Test GetRoutingRule
        /// </summary>
        [Test]
        public void GetRoutingRuleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //var response = instance.GetRoutingRule(name);
            //Assert.IsInstanceOf<RoutingRuleXO> (response, "response is RoutingRuleXO");
        }
        
        /// <summary>
        /// Test GetRoutingRules
        /// </summary>
        [Test]
        public void GetRoutingRulesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetRoutingRules();
            //Assert.IsInstanceOf<List<RoutingRuleXO>> (response, "response is List<RoutingRuleXO>");
        }
        
        /// <summary>
        /// Test UpdateRoutingRule
        /// </summary>
        [Test]
        public void UpdateRoutingRuleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //RoutingRuleXO body = null;
            //instance.UpdateRoutingRule(name, body);
            
        }
        
    }

}
