/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing SearchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SearchApiTests
    {
        private SearchApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SearchApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SearchApi
            //Assert.IsInstanceOfType(typeof(SearchApi), instance, "instance is a SearchApi");
        }

        
        /// <summary>
        /// Test Search
        /// </summary>
        [Test]
        public void SearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string continuationToken = null;
            //string sort = null;
            //string direction = null;
            //int? timeout = null;
            //string q = null;
            //string repository = null;
            //string format = null;
            //string group = null;
            //string name = null;
            //string version = null;
            //string md5 = null;
            //string sha1 = null;
            //string sha256 = null;
            //string sha512 = null;
            //string prerelease = null;
            //string conanBaseVersion = null;
            //string conanChannel = null;
            //string dockerImageName = null;
            //string dockerImageTag = null;
            //string dockerLayerId = null;
            //string dockerContentDigest = null;
            //string mavenGroupId = null;
            //string mavenArtifactId = null;
            //string mavenBaseVersion = null;
            //string mavenExtension = null;
            //string mavenClassifier = null;
            //string npmScope = null;
            //string nugetId = null;
            //string nugetTags = null;
            //string p2PluginName = null;
            //string pypiClassifiers = null;
            //string pypiDescription = null;
            //string pypiKeywords = null;
            //string pypiSummary = null;
            //string rubygemsDescription = null;
            //string rubygemsPlatform = null;
            //string rubygemsSummary = null;
            //string yumArchitecture = null;
            //var response = instance.Search(continuationToken, sort, direction, timeout, q, repository, format, group, name, version, md5, sha1, sha256, sha512, prerelease, conanBaseVersion, conanChannel, dockerImageName, dockerImageTag, dockerLayerId, dockerContentDigest, mavenGroupId, mavenArtifactId, mavenBaseVersion, mavenExtension, mavenClassifier, npmScope, nugetId, nugetTags, p2PluginName, pypiClassifiers, pypiDescription, pypiKeywords, pypiSummary, rubygemsDescription, rubygemsPlatform, rubygemsSummary, yumArchitecture);
            //Assert.IsInstanceOf<PageComponentXO> (response, "response is PageComponentXO");
        }
        
        /// <summary>
        /// Test SearchAndDownloadAssets
        /// </summary>
        [Test]
        public void SearchAndDownloadAssetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sort = null;
            //string direction = null;
            //int? timeout = null;
            //string q = null;
            //string repository = null;
            //string format = null;
            //string group = null;
            //string name = null;
            //string version = null;
            //string md5 = null;
            //string sha1 = null;
            //string sha256 = null;
            //string sha512 = null;
            //string prerelease = null;
            //string conanBaseVersion = null;
            //string conanChannel = null;
            //string dockerImageName = null;
            //string dockerImageTag = null;
            //string dockerLayerId = null;
            //string dockerContentDigest = null;
            //string mavenGroupId = null;
            //string mavenArtifactId = null;
            //string mavenBaseVersion = null;
            //string mavenExtension = null;
            //string mavenClassifier = null;
            //string npmScope = null;
            //string nugetId = null;
            //string nugetTags = null;
            //string p2PluginName = null;
            //string pypiClassifiers = null;
            //string pypiDescription = null;
            //string pypiKeywords = null;
            //string pypiSummary = null;
            //string rubygemsDescription = null;
            //string rubygemsPlatform = null;
            //string rubygemsSummary = null;
            //string yumArchitecture = null;
            //instance.SearchAndDownloadAssets(sort, direction, timeout, q, repository, format, group, name, version, md5, sha1, sha256, sha512, prerelease, conanBaseVersion, conanChannel, dockerImageName, dockerImageTag, dockerLayerId, dockerContentDigest, mavenGroupId, mavenArtifactId, mavenBaseVersion, mavenExtension, mavenClassifier, npmScope, nugetId, nugetTags, p2PluginName, pypiClassifiers, pypiDescription, pypiKeywords, pypiSummary, rubygemsDescription, rubygemsPlatform, rubygemsSummary, yumArchitecture);
            
        }
        
        /// <summary>
        /// Test SearchAssets
        /// </summary>
        [Test]
        public void SearchAssetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string continuationToken = null;
            //string sort = null;
            //string direction = null;
            //int? timeout = null;
            //string q = null;
            //string repository = null;
            //string format = null;
            //string group = null;
            //string name = null;
            //string version = null;
            //string md5 = null;
            //string sha1 = null;
            //string sha256 = null;
            //string sha512 = null;
            //string prerelease = null;
            //string conanBaseVersion = null;
            //string conanChannel = null;
            //string dockerImageName = null;
            //string dockerImageTag = null;
            //string dockerLayerId = null;
            //string dockerContentDigest = null;
            //string mavenGroupId = null;
            //string mavenArtifactId = null;
            //string mavenBaseVersion = null;
            //string mavenExtension = null;
            //string mavenClassifier = null;
            //string npmScope = null;
            //string nugetId = null;
            //string nugetTags = null;
            //string p2PluginName = null;
            //string pypiClassifiers = null;
            //string pypiDescription = null;
            //string pypiKeywords = null;
            //string pypiSummary = null;
            //string rubygemsDescription = null;
            //string rubygemsPlatform = null;
            //string rubygemsSummary = null;
            //string yumArchitecture = null;
            //var response = instance.SearchAssets(continuationToken, sort, direction, timeout, q, repository, format, group, name, version, md5, sha1, sha256, sha512, prerelease, conanBaseVersion, conanChannel, dockerImageName, dockerImageTag, dockerLayerId, dockerContentDigest, mavenGroupId, mavenArtifactId, mavenBaseVersion, mavenExtension, mavenClassifier, npmScope, nugetId, nugetTags, p2PluginName, pypiClassifiers, pypiDescription, pypiKeywords, pypiSummary, rubygemsDescription, rubygemsPlatform, rubygemsSummary, yumArchitecture);
            //Assert.IsInstanceOf<PageAssetXO> (response, "response is PageAssetXO");
        }
        
    }

}
