/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing SecurityManagementPrivilegesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SecurityManagementPrivilegesApiTests
    {
        private SecurityManagementPrivilegesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SecurityManagementPrivilegesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecurityManagementPrivilegesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SecurityManagementPrivilegesApi
            //Assert.IsInstanceOfType(typeof(SecurityManagementPrivilegesApi), instance, "instance is a SecurityManagementPrivilegesApi");
        }

        
        /// <summary>
        /// Test CreatePrivilege
        /// </summary>
        [Test]
        public void CreatePrivilegeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ApiPrivilegeWildcardRequest body = null;
            //instance.CreatePrivilege(body);
            
        }
        
        /// <summary>
        /// Test CreatePrivilege1
        /// </summary>
        [Test]
        public void CreatePrivilege1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ApiPrivilegeApplicationRequest body = null;
            //instance.CreatePrivilege1(body);
            
        }
        
        /// <summary>
        /// Test CreatePrivilege2
        /// </summary>
        [Test]
        public void CreatePrivilege2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ApiPrivilegeRepositoryContentSelectorRequest body = null;
            //instance.CreatePrivilege2(body);
            
        }
        
        /// <summary>
        /// Test CreatePrivilege3
        /// </summary>
        [Test]
        public void CreatePrivilege3Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ApiPrivilegeRepositoryAdminRequest body = null;
            //instance.CreatePrivilege3(body);
            
        }
        
        /// <summary>
        /// Test CreatePrivilege4
        /// </summary>
        [Test]
        public void CreatePrivilege4Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ApiPrivilegeRepositoryViewRequest body = null;
            //instance.CreatePrivilege4(body);
            
        }
        
        /// <summary>
        /// Test CreatePrivilege5
        /// </summary>
        [Test]
        public void CreatePrivilege5Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ApiPrivilegeScriptRequest body = null;
            //instance.CreatePrivilege5(body);
            
        }
        
        /// <summary>
        /// Test DeletePrivilege
        /// </summary>
        [Test]
        public void DeletePrivilegeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string privilegeId = null;
            //instance.DeletePrivilege(privilegeId);
            
        }
        
        /// <summary>
        /// Test GetPrivilege
        /// </summary>
        [Test]
        public void GetPrivilegeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string privilegeId = null;
            //var response = instance.GetPrivilege(privilegeId);
            //Assert.IsInstanceOf<ApiPrivilege> (response, "response is ApiPrivilege");
        }
        
        /// <summary>
        /// Test GetPrivileges
        /// </summary>
        [Test]
        public void GetPrivilegesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetPrivileges();
            //Assert.IsInstanceOf<List<ApiPrivilege>> (response, "response is List<ApiPrivilege>");
        }
        
        /// <summary>
        /// Test UpdatePrivilege
        /// </summary>
        [Test]
        public void UpdatePrivilegeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string privilegeId = null;
            //ApiPrivilegeWildcardRequest body = null;
            //instance.UpdatePrivilege(privilegeId, body);
            
        }
        
        /// <summary>
        /// Test UpdatePrivilege1
        /// </summary>
        [Test]
        public void UpdatePrivilege1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string privilegeId = null;
            //ApiPrivilegeApplicationRequest body = null;
            //instance.UpdatePrivilege1(privilegeId, body);
            
        }
        
        /// <summary>
        /// Test UpdatePrivilege2
        /// </summary>
        [Test]
        public void UpdatePrivilege2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string privilegeId = null;
            //ApiPrivilegeRepositoryViewRequest body = null;
            //instance.UpdatePrivilege2(privilegeId, body);
            
        }
        
        /// <summary>
        /// Test UpdatePrivilege3
        /// </summary>
        [Test]
        public void UpdatePrivilege3Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string privilegeId = null;
            //ApiPrivilegeRepositoryContentSelectorRequest body = null;
            //instance.UpdatePrivilege3(privilegeId, body);
            
        }
        
        /// <summary>
        /// Test UpdatePrivilege4
        /// </summary>
        [Test]
        public void UpdatePrivilege4Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string privilegeId = null;
            //ApiPrivilegeRepositoryAdminRequest body = null;
            //instance.UpdatePrivilege4(privilegeId, body);
            
        }
        
        /// <summary>
        /// Test UpdatePrivilege5
        /// </summary>
        [Test]
        public void UpdatePrivilege5Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string privilegeId = null;
            //ApiPrivilegeScriptRequest body = null;
            //instance.UpdatePrivilege5(privilegeId, body);
            
        }
        
    }

}
