/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing StatusApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StatusApiTests
    {
        private StatusApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StatusApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatusApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StatusApi
            //Assert.IsInstanceOfType(typeof(StatusApi), instance, "instance is a StatusApi");
        }

        
        /// <summary>
        /// Test GetSystemStatusChecks
        /// </summary>
        [Test]
        public void GetSystemStatusChecksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSystemStatusChecks();
            //Assert.IsInstanceOf<Dictionary<string, Result>> (response, "response is Dictionary<string, Result>");
        }
        
        /// <summary>
        /// Test IsAvailable
        /// </summary>
        [Test]
        public void IsAvailableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.IsAvailable();
            
        }
        
        /// <summary>
        /// Test IsWritable
        /// </summary>
        [Test]
        public void IsWritableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.IsWritable();
            
        }
        
    }

}
