/* 
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SonaTypeNexusRepoApi.Client;
using SonaTypeNexusRepoApi.Api;
using SonaTypeNexusRepoApi.Model;

namespace SonaTypeNexusRepoApi.Test
{
    /// <summary>
    ///  Class for testing SupportApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SupportApiTests
    {
        private SupportApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SupportApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SupportApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SupportApi
            //Assert.IsInstanceOfType(typeof(SupportApi), instance, "instance is a SupportApi");
        }

        
        /// <summary>
        /// Test Supportzip
        /// </summary>
        [Test]
        public void SupportzipTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Request body = null;
            //instance.Supportzip(body);
            
        }
        
        /// <summary>
        /// Test Supportzippath
        /// </summary>
        [Test]
        public void SupportzippathTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Request body = null;
            //var response = instance.Supportzippath(body);
            //Assert.IsInstanceOf<SupportZipXO> (response, "response is SupportZipXO");
        }
        
    }

}
